source "https://rubygems.org"
ruby '2.2.3'
gem 'sinatra', '1.1.0'
gem 'sinatra-partial'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'haml'
gem 'pg'
gem 'rake', '10.3.2'
gem 'bcrypt', '~> 3.1', '>= 3.1.10'
gem 'rest-client'
gem 'puma'
gem 'sinatra-flash', '~> 0.3.0'
